name: quiz_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  device_preview: ^1.1.0
  http: ^1.1.0
  shimmer: ^3.0.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^16.1.0
  badges: ^3.1.2
  multiselect: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/icons/
