// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25C1stw8fr7YC_1_WYO4C0aKAliAvEho',
    appId: '1:521399243756:web:ecda0b2367f9d74fff66c9',
    messagingSenderId: '521399243756',
    projectId: 'quizmaster-b358e',
    authDomain: 'quizmaster-b358e.firebaseapp.com',
    storageBucket: 'quizmaster-b358e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6G6BUOAP_u6Co5SjvjKdKTgVHylxY0s',
    appId: '1:521399243756:android:52d6f7fc98abf814ff66c9',
    messagingSenderId: '521399243756',
    projectId: 'quizmaster-b358e',
    storageBucket: 'quizmaster-b358e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGh-J-un4KL6KeH-v7y3etKzUlWW9UrVA',
    appId: '1:521399243756:ios:a716a5d215131ca1ff66c9',
    messagingSenderId: '521399243756',
    projectId: 'quizmaster-b358e',
    storageBucket: 'quizmaster-b358e.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
